routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('image/{folder}/{path}/{size?}', 'Controller@photo');


Route::get('/', function () {
    return view('front.index');
});



Route::get('about' , ['as' => 'about' , 'uses'=>'Front\HomeController@about']);
Route::get('advertising' , ['as' => 'advertising' , 'uses'=>'Front\AdvertisingController@index']);


Route::group(['prefix' => 'company' , 'as' => 'company.' , 'namespace' => 'Front\Company'], function () {

    Route::group(['namespace' => 'Auth'], function () {
        Route::get('/register', ['as' => 'register' , 'uses' => 'RegisterController@showRegistrationForm']);
        Route::post('/register', ['as' => 'register' , 'uses' => 'RegisterController@register']);



        Route::get('logout', ['as' => 'logout' , 'uses' => 'LoginController@logout']);
    });

    Route::group(['middleware' => 'auth:company'], function () {
        Route::get('/index', ['as' => 'index' , 'uses' => 'CompanyController@index']);

    });




});

app/Advertisement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Advertisement extends Model
{
    //
}

app/Company.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Company extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name','email','city','commericalNo','long','lat',
        'specialization','website','info','logo','password','remember_token',
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

}

app/CompanyUserRate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CompanyUserRate extends Model
{
    //
}

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    //
}

app/ServiceRate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ServiceRate extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/VolunteerRequest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VolunteerRequest extends Model
{
    //
}

app/VolunteerWork.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VolunteerWork extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Response;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function photo($folder, $path , $size = null)
    {
        $path = storage_path("app/$folder/".$path);

        if(!File::exists($path)) abort(404);

        $file = File::get($path);
        $type = File::mimeType($path);

        if ($size != null){
            $size = explode('x' , $size);
            if(is_numeric($size[0]) && is_numeric($size[1])){
                $width = $size[0];
                $height = $size[1];
                $manager = new \Intervention\Image\ImageManager();
                $image = $manager->make($file)->fit($width, $height, function ($constraint) {
                    $constraint->upsize();
                });

                $response = Response::make($image->encode($image->mime), 200);

                $response->header("CF-Cache-Status", 'HIF');
                $response->header("Cache-Control", 'max-age=604800, public');
                $response->header("Content-Type", $type);

                return $response;
            }else{
                abort(404);
            }
        }else{
            $manager = new \Intervention\Image\ImageManager();
            $image = $manager->make($file);

            $response = Response::make($image->encode($image->mime), 200);

            $response->header("CF-Cache-Status", 'HIF');
            $response->header("Cache-Control", 'max-age=604800, public');
            $response->header("Content-Type", $type);

            return $response;
        }
    }
}

app/Http/Controllers/Front/AdvertisingController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdvertisingController extends Controller
{
    public function index()
    {
        return view('front.advertising');
    }
}

app/Http/Controllers/Front/Company/CompanyController.php
<?php

namespace App\Http\Controllers\Front\Company;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CompanyController extends Controller
{
    public function index()
    {
        return view('front.company.index');
    }
}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function about()
    {
        return view('front.about');
    }
}

resources/views/alerts/danger.blade.php
<div class="alert alert-danger fade show" role="alert">
    <div class="alert-icon"><i class="flaticon-questions-circular-button"></i></div>
    <div class="alert-text">{{ $slot }}</div>
    <div class="alert-close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="la la-close"></i></span>
        </button>
    </div>
</div>

resources/views/alerts/success.blade.php
<div class="alert alert-success fade show" role="alert">
    <div class="alert-icon"><i class="flaticon-warning"></i></div>
    <div class="alert-text">{{ $slot }}</div>
    <div class="alert-close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="la la-close"></i></span>
        </button>
    </div>
</div>

resources/views/front/about.blade.php
@include('front.layout.header')
<style type="text/css">
    h2{
        color: #fff;
        font-size: 22px;
    }
    h1{
        color: #0A2907;
        text-decoration:anderline;
        padding: 10px;
        background-color: #fff;
    }
</style>

<center>
    <table width="80%">
        <tr>
            <td>

                <div class="div2">
                    <h1>من نحـن ؟</h1>
                    <h2>يقدم موقع معًا لنتطوع العون للمتطوعين والمنظمات مِن أجل العمل على تحقيقِ الخير في المُجتمعِ عُموماً ولأفراده خصوصاً ،و يسعى للإرتقاء بالمجتمع وخدمته ، ونشر ثقافة التطوع وحُب الخير، ويساعد على توفير التواصل مابين المتطوع والمنظمات بسهولة ، ويميز موقع معًا لنتطوع انه يوفر مساحة خاصه للمحتاجين لتوفير احتياجاتهم .
                    </h2>
                </div>
            </td>
            <td>

                <div class="div2">
                    <h1>رسالتنا: </h1>
                    <h2>التطوع هو أسلوب حياة ذا مدى عميق جداً لصناعة تغيير في نفسك أولاً ومن ثم المجتمع ، ومن احدى المصادر المهمة للخير ؛ لأنها تُساهم في عكس صورة إيجابية عن المجتمع وتوضح مدى ازدهاره ، ودائمًا نتذكر ونستشعر إن التطوّع هو العطاء بشغف، وبلا مقابل ! في عمل الخير، وبناء الإنسان وتعمير الأوطان.ولنا في التطوع حياة ~</h2>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <img src="img/xx.jpeg">
            </td>
            <td>

                <div class="div2">
                    <h1>الاهـداف : </h1>
                    <h2>* نشر ثقافة التطوع في المجتمع
                        <br>* يتيح التطوع للفرد بتعلم مهارات جديدة او تحسين مهارات يمتلكها
                        <br>*  غرس مفاهيم حب الخير</h2>
                </div>
            </td>
        </tr>
    </table>

</center>
@include('front.layout.footer')

resources/views/front/advertising.blade.php
@include('front.layout.header')


<center>
    <div  >
        <table class="div2" width="60%">
            <tr>
                <td><h1>العنوان</h1></td> </tr>
            <tr> <td><h3 style="color: #fff;">وصف الاعلان</h3></td></tr>
            <tr><td><p style="color: #fff;">التاريخ | الوقت</p></td></tr>
            <tr><td><hr></td></tr>
            <tr>
                <td><h1>العنوان</h1></td> </tr>
            <tr> <td><h3 style="color: #fff;">وصف الاعلان</h3></td></tr>
            <tr><td><p style="color: #fff;">التاريخ | الوقت</p></td></tr>
            <tr><td><hr></td></tr>
            <tr>
                <td><h1>العنوان</h1></td> </tr>
            <tr> <td><h3 style="color: #fff;">وصف الاعلان</h3></td></tr>
            <tr><td><p style="color: #fff;">التاريخ | الوقت</p></td></tr>
            <tr><td><hr></td></tr>
        </table>
    </div>
</center>
@include('front.layout.footer')

resources/views/front/company/index.blade.php
@include('front.layout.header')
<!-- /top navigation -->
<!-- page content -->
<center>
    <h2>{{ auth('company')->user()->name }}</h2>
    <div class="mb-2">
    <img src="{{ url('image/' .  auth('company')->user()->logo . '/200x200' ) }}" alt="">
    </div>
    <table border="2" width="70%">
        <tr>
            <td>الاسم</td>
            <td>معلومات</td>
            <td>مشاهدة تقييم</td>
            <td>قبول</td>
            <td>رفض</td>
        </tr>
        <tr>
            <td>xxx</td>
            <td><a href="inf.php"><input type="submit" name="" value="معلومات" class="submit"></a></td>
            <td><a href="EV.php"><input type="submit" name="" value="مشاهدة تقييم" class="submit"></a></td>
            <td><a href="#"><input type="submit" name="" value="قبول" class="submit"></a></td>
            <td><a href="#"><input type="submit" name="" value="رفض" class="submit"></a></td>

        </tr>
    </table>
</center>

@include('front.layout.footer')

resources/views/front/index.blade.php
@include('front.layout.header')
<center>
<div style="background-color: #82A669;
 border-radius: 50%;
 -webkit-border-radius: 50%;
  -moz-border-radius: 50%;
  width: 30%;
  height: 50%;" >
  <br>
  <br>
<img src="{{ asset('front/img/logo.png') }}" width="300px" height="300px">
</div></center>
@include('front.layout.footer')

resources/views/front/layout/footer.blade.php
<br>
<br>
<br>
<br>


<footer>
    <CENTER>
        <p>جميع الحقوق محفوظة لموقع غيث التطوعي &copy; 2019 </p>
    </CENTER>
</footer></div>
</body>
</html>

resources/views/front/layout/header.blade.php
<html>
<head>
    <title>Ghaith voluGhaith volunteer</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('front/css.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
<header>
    <div style="display: inline; font-size: 40px; float: right;">

        <a href="{{ url('/') }}"><img src="{{ asset('front/img/logo.png') }}" width="400" height="230"> </a>
    </div>

    <ul>
        <div style="float: left;">
            <li><a class="Lists" href="{{ route('advertising') }}">الاعلانات المتاحة حاليا</a></li>


            <li><a class="Lists" href="{{ url('/') }}">الرئيسية |</a></li>
            <li><a class="Lists" href="{{ url('/about') }}">نبذة |</a></li>
            <li class="dropdown"><a class="Lists" href="javascript:void(0)">الانضمام |</a>
                <div class="dropdown-content">
                    <a href="{{ route('company.register') }}">منظمة تطوعية</a>
                    <a href="volunteer.php">متطوع</a>
                    <a href="needy.php">محتاج</a>
                    <a href="login.php">دخول</a></div>
            </li>
        </div>
    </ul>


    <hr>
</header>
<div class="div">
    <br><br><br>